import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { type FC, useState } from "react";
import { api } from "../../utils/api";
import dynamic from "next/dynamic";
import { Post, Tag } from "@prisma/client";
import { z } from "zod";




const QuillNoSSRWrapper = dynamic(() => import('react-quill'), {
  ssr: false,
  loading: () => <p>Loading ...</p>,
})

const modules = {

  toolbar: [
    [{ header: '1' }, { header: '2' }, { font: [] }],
    [{ size: [] }],
    ['bold', 'italic', 'underline', 'strike', 'blockquote', 'code-block'],
    [
      { list: 'ordered' },
      { list: 'bullet' },
      { indent: '-1' },
      { indent: '+1' },
    ],
    ['link', 'image', 'video'],
    ['clean'],
  ],
  clipboard: {
    // toggle to add extra line breaks when pasting HTML:
    matchVisual: false,
  },
}
/*
 * Quill editor formats
 * See https://quilljs.com/docs/formats/
 */
const formats = [
  'header',
  'font',
  'size',
  'bold',
  'italic',
  'underline',
  'strike',
  'blockquote',
  'code-block',
  'list',
  'bullet',
  'indent',
  'link',
  'image',
  'video',
]

type tags = {
  id: string | undefined,
  desc:string
}
const Form: FC = () => {

  const [content, setContent] = useState("");
  const [tag, setTag] = useState("");
  const [tags, setTags] = useState<tags[]>([]);
  const { data: session, status } = useSession();

  const utils = api.useContext();
  const postMessage = api.post.postMessage.useMutation({
    onSettled: async () => {
      await utils.post.getAll.invalidate();
    },
  });

  return status === "authenticated" ? (
    <form
      className="flex gap-2"
      onSubmit={(event) => {
        event.preventDefault();
        postMessage.mutate({
          tag: tags,
          content,
        });
        setTags([]);
        setContent("");
      }}
    >
      <div className="flex flex-col">
        <div className="flex flex-col mb-20">
          {/* <input
            type="text"
            className="rounded-md border-2 border-zinc-800 px-4 py-2 focus:outline-none"
            placeholder="Your message..."
            minLength={2}
            maxLength={100}
            value={content}
            onChange={(event) => setContent(event.target.value)}
          /> */}
          <QuillNoSSRWrapper modules={modules} formats={formats} onChange={setContent} theme="snow" />
        </div>


        <div className="flex flex-col">
          {tags?.map((entry: tags, index) => (
            <div key={index}>
              <p>{entry.desc}</p>
            </div>
          ))}
          <div className="flex flex-row">

            <input
              type="text"
              className="rounded-md border-2 border-zinc-800 px-4 py-2 focus:outline-none"
              placeholder="tag1"
              minLength={2}
              maxLength={100}
              value={tag}
              onChange={(event) => setTag(event.target.value)}
            />
            <div className="flex flex-row">
              <div
                className="rounded-md border-2 border-zinc-800 p-2 focus:outline-none"
                onClick={(e) => { e.preventDefault(); setTags([...tags, {id:undefined, desc: tag }]); setTag(""); }}
              >

                ADD
              </div>
            </div>
          </div>

        </div>
        <button
          type="submit"
          className="rounded-md border-2 border-zinc-800 p-2 focus:outline-none"
        >
          Submit
        </button>
      </div>




    </form>
  ) : null;
};

const PostEntries: FC = () => {
  const { data: postEntries, isLoading } = api.post.getAll.useQuery();

  if (isLoading) {
    return <div>Fetching messages...</div>;
  }

  return (
    <div className="flex flex-col gap-4">
      {postEntries?.map((entry, index) => (
        <div key={index}>
          <p>{entry.content}</p>
          {entry.tag.map((obj, idx) => (<span key={idx} className="pr-2">{obj.desc}</span>))}
        </div>
      ))}
    </div>
  );
};

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  if (status === "loading") {
    return <main className="flex flex-col items-center pt-4">Loading...</main>;
  }

  return (
    <div className="flex flex-row justify-center bg-white mt-8 mx-10 p-10">
      <Head>
        <title>post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center">
        <h1 className="pt-4 text-3xl">Create New Post</h1>
        
        <div className="pt-10">
          <div>
            {session ? (
              <>
                <p className="mb-4 text-center">hi {session.user?.name}</p>
                <button
                  type="button"
                  className="mx-auto block rounded-md border-2 border-zinc-800 py-3 px-6 text-center hover:bg-neutral-700"
                  onClick={() => {
                    signOut().catch(console.log);
                  }}
                >
                  Logout
                </button>
                <div className="pt-6">
                  <Form />
                </div>
              </>
            ) : (
              <button
                type="button"
                className="mx-auto block rounded-md py-3 px-6 text-center hover:bg-neutral-700"
                onClick={() => {
                  signIn("discord").catch(console.log);
                }}
              >
                Login with Discord
              </button>
            )}
            {/* <div className="pt-10">
              <PostEntries />
            </div> */}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;